# Generated by Django 3.2 on 2021-04-09 02:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('deadline', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 4, 9))])),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tasks')),
            ],
            options={
                'ordering': ['deadline', 'id'],
            },
        ),
    ]
